sherlockode_configuration:
  upload:
    uri_prefix: var/cfguploads
    directory: '%kernel.project_dir%/public/var/cfguploads'
  entity_class:
    parameter: App\Entity\Parameter
  parameters:
    force_close:
      label: Forzar cierre del formulario
      type: checkbox
      options:
        help: Hace que el formulario esté cerrado aunque aún haya hueco
        default: False
    max_applications:
      label: Máximo inscripciones
      type: simple
      default_value: 70
      options:
        subtype: Symfony\Component\Form\Extension\Core\Type\IntegerType
        help: Número total de tarjetas que se crearán
    max_applications_perperson:
      label: Máximo de peticiones por usuario
      type: simple
      default_value: 3
      options:
        subtype: Symfony\Component\Form\Extension\Core\Type\IntegerType
        help: Peticiones que pueden hacerse desde cada IP
    cxt__date_long:
      label: Fecha Cuentos por Teléfono
      type: simple
      default_value: 21 de marzo de 20XX
      options:
        help: La fecha que aparece en la web
    cxt__date_calls:
      label: Fecha de las llamadas de Cuentos por Teléfono
      type: simple
      default_value: 21 de marzo de 20XX de 6 a 9
      options:
        help: La fecha y hora de las llamadas
    cxt__cartel:
      label: Cartel de Cuentos por Teléfono
      type: image
    pxt__date_long:
      label: Fecha Poemas por Teléfono
      type: simple
      default_value: 23 de abril de 20XX
    pxt__date_calls:
      label: Fecha de las llamadas de Poemas por Teléfono
      type: simple
      default_value: 23 de abril de 20XX de 6 a 9
    pxt__cartel:
      label: Cartel de Poemas por Teléfono
      type: image
