twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        cypxt_title: Poemas por Teléfono
        cypxt_date: Lunes, 22 de Marzo de 2021
        cypxt_hashtag: poemasxtelefono
