twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        cypxtpar: '@App\Service\CypxtParams'
        cypxtconf: '@App\Service\CypxtConfig'
        mel:
            instagram: montando_el_local
            twitter: montandoellocal
            tiktok: montando_el_local
