image: php:7.3-alpine

cache:
  paths:
    - vendor/
    - var/cache

variables:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  COMPOSER_MEMORY_LIMIT: "-1"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - public/build/
  before_script:
     - apk add yarn
  script:
     - yarn install --no-dev
     - yarn encore prod

build composer:
  stage: build
  only:
    changes:
      - composer.lock
  artifacts:
    paths:
      - vendor/
  before_script:
    - apk add composer
  script:
    - php -v
    - composer install --no-dev --optimize-autoloader --no-interaction --no-plugins --no-scripts --no-suggest

# - lftp -c "set ftp:ssl-allow no; set ftp:list-options -a; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -c --verbose -Re -P 10 ./node_modules $FTP_PATH/node_modules"

# upload composer:
#   stage: deploy
#   only:
#     changes:
#       - composer.lock
#   before_script:
#     - apk add lftp
#   script:
#     - lftp -c "set ftp:ssl-allow no; set ftp:list-options -a; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -c --verbose -Re -P 10 ./vendor $FTP_PATH/vendor"

upload:
  stage: deploy
  before_script:
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan pxt.montandoellocal.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -rltvz --delete --exclude-from=.ftpignore --exclude=vendor/ --exclude=node_modules/ ./ ec2-user@pxt.montandoellocal.com:/var/www/pxt/
    - ssh ec2-user@pxt.montandoellocal.com whoami
    - '[ -d "node_modules/" ] && rsync -rltvz --delete ./node_modules ec2-user@pxt.montandoellocal.com:/var/www/pxt/node_modules'
    - '[ -d "vendor/" ] && rsync -rltvz --delete ./vendor ec2-user@pxt.montandoellocal.com:/var/www/pxt/vendor'
    - ssh ec2-user@pxt.montandoellocal.com 'cd /var/www/pxt && php bin/console cache:clear && php bin/console cache:warmup'