image: php:7.3-alpine

cache:
  paths:
    - vendor/
    - var/cache

variables:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  COMPOSER_MEMORY_LIMIT: "-1"

stages:
  - build
  - test
  - upload

build:
  stage: build
  artifacts:
    paths:
      - vendor/
      - node_modules/
  before_script:
    - apk add composer yarn
  script:
    - php -v
    - php -r "echo ini_get('memory_limit').PHP_EOL;"
    - echo $COMPOSER_MEMORY_LIMIT
    - composer install --no-dev --optimize-autoloader --no-interaction --no-plugins --no-scripts --no-suggest
    - yarn install --no-dev

upload:
  stage: upload
  before_script:
    - apk add lftp
  script:
    - lftp -c "set ftp:list-options -a; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Re ./ $FTP_PATH --exclude-glob-from .ftpignore"