image: php:7.3-alpine

cache:
  paths:
    - vendor/
    - var/cache

variables:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  COMPOSER_MEMORY_LIMIT: "-1"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - public/build/
  before_script:
     - apk add yarn
  script:
     - yarn install --no-dev
     - yarn encore prod

upload:
  stage: deploy
  before_script:
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan cypxt.montandoellocal.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ./upload.sh
    - ssh cypxt@cypxt.montandoellocal.com "cd $WEB_DIR && ./postdeploy.sh"