stats:
  path: /estadisticas
  controller: App\Controller\StatsController::index

callme_success:
  path: /success
  controller: App\Controller\CallMeController::main

api_stats:
  path: /api/stats
  controller: App\Controller\StatsController::api