#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  host: "{subdomain}.{wildcard}"
  controller: App\Controller\CallMeController::main
  requirements:
    subdomain: cxt|pxt
  defaults:
    subdomain: cxt

stats:
  path: /estadisticas
  controller: App\Controller\StatsController::index

callme_success:
  path: /success
  controller: App\Controller\CallMeController::main

admin:
  path: /lineas
  controller: App\Controller\LineasController::main

api_stats:
  path: /api/stats
  controller: App\Controller\StatsController::api