#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\CallMeController::main

stats:
  path: /estadisticas
  controller: App\Controller\StatsController::index

callme_success:
  path: /success
  controller: App\Controller\CallMeController::main

admin:
  path: /lineas
  controller: App\Controller\LineasController::main